#!/usr/bin/env -S uv run python
# -*- mode: python -*-
import argparse, tty, termios, socket

def parse_args():
    par = argparse.ArgumentParser()
    par.add_argument('-k', action='store_true', default=False, help='kbhit mode')
    par.add_argument('-p', default=6600, type=int, help='port number')
    return par.parse_known_args()

def getkey():
    fd = sys.stdin.fileno()
    original_attributes = termios.tcgetattr(fd)
    try:
        tty.setraw(sys.stdin.fileno())
        ch = sys.stdin.read(1)
        termios.tcsetattr(fd, termios.TCSADRAIN, original_attributes)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, original_attributes)        
    return ch

arg, w = parse_args()
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
server_address = ('127.0.0.1', arg.p)

#single-shot mode
if len(w) > 0:
    msg = w[0]
    for i in w[1:]: msg += ' ' + i
    #print(msg)

    sock.sendto(msg.encode(), server_address)
    sock.close()

#console mode
elif arg.k == False:
    while(True):
        msg = input('msg: ')
        push.send(msg.encode())
        if msg == 'quit': break

#kbhit mode
else:
    while(True):
        k = getkey()
        if k == '.': break
    
        elif k == 'q': #quit
            push.send(b'quit')
            print('./quit')
            continue
        
        elif k == '-': #reset
            push.send(b'reset')
            print('reset')
            continue
            
        push.send(k.encode())
        print(k)
        
sock.close()
